import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '../Components/Hero';
import Slider from '../Components/Slider';
import { SliderData } from '../Components/SliderData';
import Instagram from '../Components/Instagram';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Makeup by Insert-Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Makeup by InsertName' message='Be your most beautiful self' />
      <Slider slides={SliderData} />
      <Instagram />
    </>
  )
}